### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at src/wg.rs:944:38

### ISSUE THREAD

**Issue by Tathar** [Tathar/wg-turn#1]
Aug  1 11:48:02 turris wg-turn[4395]: bootstraped ipv4
Aug  1 11:48:10 turris wg-turn[4395]: Receve Self Syn message
Aug  1 11:48:16 turris wg-turn[4395]: Receve Syn for 11111111111111111111111111111111= from 1.2.3.4:51821
Aug  1 11:48:16 turris wg-turn[4395]: Send Syn/Ack for11111111111111111111111111111111= to  1.2.3.4:51821
Aug  1 11:48:16 turris wg-turn[4395]: Receve SynAck for 11111111111111111111111111111111= from  1.2.3.4:51821
Aug  1 11:48:16 turris wg-turn[4395]: Send Ack for 11111111111111111111111111111111= to 1.2.3.4:51821
Aug  1 11:48:28 turris wg-turn[4395]: send error in new_check for 11111111111111111111111111111111= to 4.3.2.1:51820 with Connection refused (os error 111)
Aug  1 11:47:37 turris wg-turn[4395]: new_check return for  1.2.3.4:51821
Aug  1 11:47:37 turris wg-turn[4395]: thread 'tokio-runtime-worker' panicked at src/wg.rs:944:38:
Aug  1 11:47:37 turris wg-turn[4395]: called `Result::unwrap()` on an `Err` value: SystemTimeError(41.80162902s)
Aug  1 11:47:37 turris wg-turn[4395]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Tathar** [comment]
patch 69c3c140e54b83f6bd4148e2d077342fb48c7e2c
